//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadonsp
    {
        public string Mahoadon { get; set; }
        public Nullable<int> Masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> giasp { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
