//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietghe
    {
        public int Machieu { get; set; }
        public int Status { get; set; }
        public int Machitietghe { get; set; }
        public Nullable<int> Maghe { get; set; }
    
        public virtual suatchieu suatchieu { get; set; }
        public virtual ghe ghe { get; set; }
    }
}
