//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsuatchieu
    {
        public int Machitietsuatchieu { get; set; }
        public Nullable<int> Machieu { get; set; }
        public Nullable<int> Maphim { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<decimal> giave { get; set; }
    
        public virtual suatchieu suatchieu { get; set; }
        public virtual phim phim { get; set; }
    }
}
