//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ghe()
        {
            this.chitietghes = new HashSet<chitietghe>();
            this.vexems = new HashSet<vexem>();
        }
    
        public int Maghe { get; set; }
        public int Soghe { get; set; }
        public string Row { get; set; }
        public int Maphong { get; set; }
        public Nullable<int> trangthaighe { get; set; }
        public Nullable<int> maloaighe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietghe> chitietghes { get; set; }
        public virtual phong phong { get; set; }
        public virtual loaighe loaighe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vexem> vexems { get; set; }
    }
}
