//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadon()
        {
            this.vexems = new HashSet<vexem>();
        }
    
        public string Makhachhang { get; set; }
        public string Manhanvien { get; set; }
        public Nullable<int> maphim { get; set; }
        public Nullable<int> soluongve { get; set; }
        public Nullable<decimal> giaveduocgiam { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string Mahoadon { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        public virtual phim phim { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vexem> vexems { get; set; }
    }
}
