//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.accounts = new HashSet<account>();
            this.baocaosucoes = new HashSet<baocaosuco>();
            this.hoadons = new HashSet<hoadon>();
            this.hoadonsanphams = new HashSet<hoadonsanpham>();
            this.phieuchis = new HashSet<phieuchi>();
            this.quanlythuchis = new HashSet<quanlythuchi>();
        }
    
        public string Manhanvien { get; set; }
        public string hoten { get; set; }
        public string Email { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<int> Machucvu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<baocaosuco> baocaosucoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonsanpham> hoadonsanphams { get; set; }
        public virtual phanquyen phanquyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieuchi> phieuchis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quanlythuchi> quanlythuchis { get; set; }
    }
}
