//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanloaighebyphong
    {
        public int idpl { get; set; }
        public int Maphong { get; set; }
        public int Maloai { get; set; }
    
        public virtual loaighe loaighe { get; set; }
        public virtual phong phong { get; set; }
    }
}
