//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuchi
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<System.TimeSpan> thoigian { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public string Manhanvien { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
