//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadonsps = new HashSet<chitiethoadonsp>();
            this.hoadonsanphams = new HashSet<hoadonsanpham>();
        }
    
        public int Masp { get; set; }
        public string Tensanpham { get; set; }
        public Nullable<int> Madanhmuc { get; set; }
        public Nullable<int> soluong { get; set; }
        public byte[] hinhanh { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadonsp> chitiethoadonsps { get; set; }
        public virtual danhmucsp danhmucsp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonsanpham> hoadonsanphams { get; set; }
    }
}
