//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemquanlyrapchieuphim.DTO.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class suatchieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suatchieu()
        {
            this.chitietghes = new HashSet<chitietghe>();
            this.chitietsuatchieux = new HashSet<chitietsuatchieu>();
            this.vexems = new HashSet<vexem>();
        }
    
        public int Machieu { get; set; }
        public Nullable<int> Maphong { get; set; }
        public Nullable<int> Maphim { get; set; }
        public Nullable<System.DateTime> thoigianchieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietghe> chitietghes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietsuatchieu> chitietsuatchieux { get; set; }
        public virtual phim phim { get; set; }
        public virtual phong phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vexem> vexems { get; set; }
    }
}
